postgres:
  outputs:

    staging:
      type: postgres
      threads: 1
      host: localhost
      port: 5434
      user: postgres
      pass: pepe
      dbname: brava_staging
      schema: staging_schema

    staging2:
      type: postgres
      threads: 1
      host: localhost
      port: 5434
      user: postgres
      pass: pepe
      dbname: brava_staging
      schema: public

  target: staging2
