snowflake:
  outputs:
    dev:
      account: gm18335.east-us-2.azure
      database: ANALYTICS
      password: o8nT.H1L
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: NOESNESTOR
      warehouse: TRANSFORMING
  target: dev

postgres:
  outputs:

    staging:
      type: postgres
      threads: 1
      host: localhost
      port: 5434
      user: postgres
      pass: pepe
      dbname: brava_staging
      schema: staging_schema

    staging2:
      type: postgres
      threads: 1
      host: localhost
      port: 5434
      user: postgres
      pass: pepe
      dbname: brava_staging
      schema: public

  target: staging2
