postgres:
  outputs:

    staging:
      type: postgres
      threads: 1
      host: 127.0.0.1
      port: 5434
      user: postgres
      pass: postgres
      dbname: postgres
      schema: staging_schema

    staging2:
      type: postgres
      threads: 1
      host: 127.0.0.1
      port: 5434
      user: postgres
      pass: postgres
      dbname: postgres
      schema: public

  target: staging
