postgres:
  outputs:
    dw:
      type: postgres
      threads: 1
      host: postgres-dw
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: public

  target: dw
